# Generated by Django 5.2 on 2025-04-26 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_order_customer_verified_alter_order_id'),
        ('employee', '0003_alter_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.vehicle'),
        ),
    ]
