# Generated by Django 5.2 on 2025-04-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('van', 'Van'), ('motorcycle', 'Motorcycle'), ('e-bike', 'Electric Bicycle'), ('pickup', 'Pickup'), ('lorry', 'Lorry')], max_length=20)),
                ('plate_number', models.CharField(max_length=20)),
                ('in_use', models.BooleanField(default=False)),
            ],
        ),
    ]
