# Generated by Django 5.2 on 2025-04-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('van', 'Van'), ('motorcycle', 'Motorcycle'), ('e-bike', 'Electric Bicycle'), ('pickup', 'Pickup'), ('lorry', 'Lorry'), ('bike', 'Bike')], max_length=20),
        ),
    ]
